-- Customer orders and order frequency 

WITH CTE1 AS(
SELECT C.CUSTOMER_ID,O.ORDER_ID,C.FIRST_NAME,C.LAST_NAME,COUNT(O.CUSTOMER_ID) AS ORDERS_COUNT FROM customers C
LEFT JOIN ORDERS O
ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID,C.FIRST_NAME,C.LAST_NAME,O.ORDER_ID),
CTE2 AS(
SELECT O.ORDER_ID, ROUND(SUM(OI.FINAL_PRICE),2) AS AMOUNT FROM ORDERS O
LEFT JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
GROUP BY O.ORDER_ID),
CTE3 AS(
SELECT * FROM CTE1 LEFT JOIN CTE2
USING (ORDER_ID))
SELECT CTE3.CUSTOMER_ID,CTE3.FIRST_NAME,CTE3.LAST_NAME,SUM(CTE3.ORDERS_COUNT) AS TOTAL_ORDERS ,ROUND(SUM(CTE3.AMOUNT),2) AS TOTAL_REVENUE FROM CTE3
GROUP BY CTE3.CUSTOMER_ID,CTE3.FIRST_NAME,CTE3.LAST_NAME
ORDER BY TOTAL_ORDERS DESC;
