--  Product-wise sales and inventory trends

WITH PRODUCT_TABLE_DATA AS(
SELECT OI.PRODUCT_ID, COUNT(OI.PRODUCT_ID) AS PRODUCT_ORDERS_COUNT,
SUM(OI.QUANTITY) AS ORDERED_PRODUCT_COUNT,
ROUND(SUM(OI.FINAL_PRICE),2) AS REVENUE_GENERATED FROM ORDER_ITEMS OI
GROUP BY OI.PRODUCT_ID),

STOCKS_TABLE_DATA AS (
SELECT ST.PRODUCT_ID,SUM(ST.QUANTITY) AS REMAINING_STOCKS FROM STOCKS ST
GROUP BY ST.PRODUCT_ID)

SELECT STA.PRODUCT_ID,
PTD.PRODUCT_ORDERS_COUNT,PTD.ORDERED_PRODUCT_COUNT,(REMAINING_STOCKS + ORDERED_PRODUCT_COUNT) AS INITIAL_STOCKS,STA.REMAINING_STOCKS,
PTD.REVENUE_GENERATED
FROM STOCKS_TABLE_DATA STA
LEFT JOIN PRODUCT_TABLE_DATA PTD
USING (PRODUCT_ID)
ORDER BY ORDERED_PRODUCT_COUNT DESC;