-- Staff performance reports 
WITH CTE1 AS (
SELECT CO.STAFF_ID,CO.FIRST_NAME,CO.LAST_NAME,CO.STORE_ID,CO.EMAIL,CO.PHONE,COUNT(O.ORDER_ID) AS NO_OF_ORDERS FROM STAFFS CO
LEFT JOIN ORDERS O 
ON CO.STAFF_ID = O.STAFF_ID
GROUP BY CO.STAFF_ID,CO.FIRST_NAME,CO.LAST_NAME,CO.STORE_ID),

CTE2 AS(
SELECT ORDERS.STAFF_ID,ORDERS.STORE_ID,ROUND(SUM(ORDER_ITEMS.FINAL_PRICE),2) AS REVENUE FROM ORDERS
INNER JOIN ORDER_ITEMS 
ON ORDERS.ORDER_ID = ORDER_ITEMS.ORDER_ID
GROUP BY ORDERS.STAFF_ID,ORDERS.STORE_ID)

SELECT CTE1.STAFF_ID,CTE1.FIRST_NAME,CTE1.LAST_NAME,CTE1.STORE_ID,
CTE1.EMAIL,CTE1.NO_OF_ORDERS,CTE2.REVENUE FROM CTE1
LEFT JOIN CTE2
USING(STAFF_ID)
ORDER BY NO_OF_ORDERS DESC;

