--  Store-wise and Region-wise sales analysis

SELECT S.STORE_ID,S.STORE_NAME,S.STATE,COUNT(O.STORE_ID) AS TOTAL_ORDERS FROM STORES S
INNER JOIN ORDERS O
ON S.STORE_ID = O.STORE_ID
GROUP BY S.STORE_ID,S.STORE_NAME;

-- REVENUE FROM EACH STORE
WITH TOTAL_ORDERS_REVENUE AS (
SELECT O.ORDER_ID,O.STORE_ID,S.STORE_NAME,S.CITY,S.STATE,SUM(OI.FINAL_PRICE) AS TOTAL_REVENUE FROM ORDERS O 
INNER JOIN ORDER_ITEMS OI
ON O.ORDER_ID = OI.ORDER_ID
INNER JOIN STORES S
ON S.STORE_ID = O.STORE_ID
GROUP BY O.ORDER_ID
ORDER BY O.STORE_ID)

SELECT STORE_ID,STORE_NAME,CITY,STATE,ROUND(SUM(TOTAL_REVENUE), 2) as Revenue  FROM TOTAL_ORDERS_REVENUE
GROUP BY STORE_ID,STORE_NAME
ORDER BY REVENUE DESC;

